global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: traefik
    static_configs:
      - targets: ['public-node-red_traefik_1.public-node-red:8082']
  - job_name: node-red
    static_configs:
      - targets: ['public-node-red_node-red_1.public-node-red:1880']
