log:
  level: INFO

ping: {}

entryPoints:
  websecure:
    address: ":443"
  metrics:
    address: ":9090"
  metrics-treafik:
    address: ":8082"
  home-assistant:
    address: ":8123"

metrics:
  prometheus:
    entryPoint: metrics-treafik

providers:
  docker:
    network: public-node-red_default
    exposedByDefault: false

certificatesResolvers:
  tls-resolver:
    acme:
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
      httpChallenge:
        entryPoint: websecure

#http:
#  services:
#    home-assistant:
#       loadBalancer:
#        servers:
#          - address: "http://host.docker.internal:8123"
